# Week 8 (Tue) - Class Activities in CS 315

You are given the file `netflix_top10_countries.tsv` in the folder data, solve the following tasks using it.

**Table of Contents**

1. [Q1: Load the file](#q1)
2. [Q2: Show number of rows](#q2)
3. [Q3: Show column names](#q3)
4. [Q4: Show number of total countries](#q4)
5. [Q5: Show number of TV series](#q5)
6. [Q6: Number of TV series in South Korea](#q6)
7. [Q7: Total weeks of Squid Games in Italy ](#q7)
8. [Q8: Time frame for a given country](#q8)
9. [Q9: Is number of weeks in ranking equal?](#q9)
10. [Q10: Country with fewest weeks](#q10)

<a id="q1"></a>
### Q1: Load the file

In [1]:
import pandas as pd 

df = pd.read_csv("netflix_top10_countries.tsv", sep="\t")
df.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10
0,Argentina,AR,2026-10-04,Films,1,UNABOMBER,NaN,2
1,Argentina,AR,2026-10-04,Films,2,The Equalizer 3,NaN,1
2,Argentina,AR,2026-10-04,Films,3,The Substance,NaN,1
3,Argentina,AR,2026-10-04,Films,4,Demon Slayer: Kimetsu no Yaiba Infinity Castle I,NaN,1
4,Argentina,AR,2026-10-04,Films,5,What a Father!,NaN,1

<a id="q2"></a>
### Q2: Show number of rows

In [2]:
len(df)

512200

<a id="q3"></a>
### Q3: Show column names

In [3]:
df.columns

Index(['country_name', 'country_iso2', 'week', 'category', 'weekly_rank',
       'show_title', 'season_title', 'cumulative_weeks_in_top_10'],
      dtype='object')

<a id="q4"></a>
### Q4: Show number of total countries

In [4]:
df["country_name"].nunique()

94

<a id="q5"></a>
### Q5: Show number of TV series

In [5]:
df["show_title"].nunique()

12197

<a id="q6"></a>
### Q6: Number of TV series in South Korea

In [6]:
korea = df[df["country_name"] == "South Korea"]
korea["show_title"].nunique()

1568

<a id="q7"></a>
### Q7: Total weeks of Squid Game in Italy

In [7]:
italy = df[df["country_name"] == "Italy"]
squid_game = italy[italy["show_title"] == "Squid Game"]

squid_game["week"].nunique()

29

<a id="q8"></a>
### Q8: Time frame for a given country

Write a function that given a country name prints out the start and end date of their rankings.

Once you have created the function, call it for a few countries to test it.

In [8]:
def show_timeframe(country):
    country_df = df[df["country_name"] == country]
    
    start = country_df["week"].min()
    end = country_df["week"].max()
    
    print(f"{country}: {start} to {end}")

show_timeframe("South Korea")
show_timeframe("Italy")
show_timeframe("Russia")

South Korea: 2021-07-04 to 2026-10-04
Italy: 2021-07-04 to 2026-10-04
Russia: 2021-07-04 to 2022-02-27

<a id="q9"></a>
### Q9: Is number of weeks equal for each country?

The total number of weeks in the rankings is `len(df['week'].unique())`.

The total number of countries is `len(df['country_name'].unique())`.  

For every week, each country has 20 rows.   

If they all stayed the same number of weeks, then the product of these three weeks would be the same as the total number of rows.

In [9]:
weeks_per_country = df.groupby("country_name")["week"].nunique()

weeks_per_country.nunique() == 1

False

We should have expected this to be `False` since we saw in Q8 that Russia stopped being in the rankings after it attacked Ukraine in February 2022.

<a id="q10"></a>
### Q10: Country with fewest weeks

Write a one-liner that will show the country with the fewest weeks in the Netflix rankings

In [10]:
df.groupby("country_name")["week"].nunique().idxmin()

'Russia'

## F1 Ranking Scores

In [11]:
def rank2score(rank):
    points = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1]
    return points[rank - 1]

rank2score(1)

25

In [12]:

print(rank2score(1))
print(rank2score(5))
print(rank2score(10))

25
10
1

In [13]:

df["score"] = df["weekly_rank"].apply(rank2score)
df.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10,score
0,Argentina,AR,2026-10-04,Films,1,UNABOMBER,NaN,2,25
1,Argentina,AR,2026-10-04,Films,2,The Equalizer 3,NaN,1,18
2,Argentina,AR,2026-10-04,Films,3,The Substance,NaN,1,15
3,Argentina,AR,2026-10-04,Films,4,Demon Slayer: Kimetsu no Yaiba Infinity Castle I,NaN,1,12
4,Argentina,AR,2026-10-04,Films,5,What a Father!,NaN,1,10

## True Beauty: Scores by Country

In [14]:
true_beauty = df[
    (df["show_title"] == "True Beauty") &
    (df["category"] == "TV")
]

true_beauty.head()

,country_name,country_iso2,week,category,weekly_rank,show_title,season_title,cumulative_weeks_in_top_10,score
2858,Argentina,AR,2024-01-14,TV,9,True Beauty,True Beauty: Limited Series,5,2
2874,Argentina,AR,2024-01-07,TV,5,True Beauty,True Beauty: Limited Series,4,10
2894,Argentina,AR,2023-12-31,TV,5,True Beauty,True Beauty: Limited Series,3,10
2913,Argentina,AR,2023-12-24,TV,4,True Beauty,True Beauty: Limited Series,2,12
2932,Argentina,AR,2023-12-17,TV,3,True Beauty,True Beauty: Limited Series,1,15

In [15]:
true_beauty_scores = (
    true_beauty
    .groupby("country_name")
    .agg(total_score=("score", "sum"),
         weeks=("week", "nunique"))
    .reset_index()
    .sort_values("total_score", ascending=False)
)

true_beauty_scores.head(10)

    country_name  total_score  weeks
3     Bangladesh          215     18
4        Bolivia          191     25
38   Philippines          180     14
33          Oman          178     18
41  Saudi Arabia          178     17
37          Peru          163     18
24      Maldives          153     15
23      Malaysia          142     14
10       Ecuador          138     17
39         Qatar          137     12

In [16]:
mask_girl = df[
    (df["show_title"] == "Mask Girl") &
    (df["category"] == "TV")
]

mask_girl_scores = (
    mask_girl
    .groupby("country_name")
    .agg(total_score=("score", "sum"),
         weeks=("week", "nunique"))
    .reset_index()
    .sort_values("total_score", ascending=False)
)

mask_girl_scores.head(10)

   country_name  total_score  weeks
61  South Korea          125      8
71      Vietnam          114      7
23    Hong Kong           99      6
26    Indonesia           85      5
66     Thailand           80      5
65       Taiwan           79      5
59    Singapore           67      4
36     Malaysia           66      5
29        Japan           60      5
51  Philippines           53      4